server:
  port: 8080

gateway:
  api-key: ${GATEWAY_API_KEY}

app:
  auth:
    jwt-secret: ${JWT_SECRET}


spring:
  application:
    name: omecca-backend
  datasource:
    url: jdbc:mysql://localhost:3306/omecca?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false

logging:
  level:
    com.omecca.omeccabackend: INFO